module.exports = {
  NUANCE_CLIENT_ID: 'NUANCE_CLIENT_ID',
  NUANCE_CLIENT_SECRET: 'NUANCE_CLIENT_SECRET',
  NUANCE_CONTEXT_TAG: 'NUANCE_CONTEXT_TAG',
  NUANCE_CHANNEL: 'NUANCE_CHANNEL',

  // optional:
  NUANCE_LANGUAGE: 'NUANCE_LANGUAGE',
  NUANCE_NLP_ANALYTICS_ENABLE: 'NUANCE_NLP_ANALYTICS_ENABLE',
  // for downloader-uploader
  NUANCE_API_URL: 'NUANCE_API_URL',
  NUANCE_ADMIN_CLIENT_ID: 'NUANCE_ADMIN_CLIENT_ID',
  NUANCE_ADMIN_CLIENT_SECRET: 'NUANCE_ADMIN_CLIENT_SECRET',
  NUANCE_PROJECT_ID: 'NUANCE_PROJECT_ID',
  NUANCE_OAUTH_URL: 'NUANCE_OAUTH_URL',
  NUANCE_NLU_ENDPOINT: 'NUANCE_NLU_ENDPOINT',
  NUANCE_DLG_ENDPOINT: 'NUANCE_DLG_ENDPOINT',

  // advanced
  NUANCE_OAUTH_MAX_RETRIES: 'NUANCE_OAUTH_MAX_RETRIES',
  NUANCE_OAUTH_RETRY_DELAY_SEC: 'NUANCE_OAUTH_RETRY_DELAY_SEC',
  NUANCE_LIBRARY: 'NUANCE_LIBRARY',
  NUANCE_SESSION_ID: 'NUANCE_SESSION_ID',
  NUANCE_SESSION_TIMEOUT_SEC: 'NUANCE_SESSION_TIMEOUT_SEC',
  NUANCE_USER_ID: 'NUANCE_USER_ID',
  NUANCE_CLIENT_DATA: 'NUANCE_CLIENT_DATA', // https://docs.nuance.com/mix/apis/event_logs/inject-content/#client-data
  NUANCE_SUPPRESS_LOG_USER_DATA: 'NUANCE_SUPPRESS_LOG_USER_DATA',
  NUANCE_INITIAL_CONTEXT: 'NUANCE_INITIAL_CONTEXT', // Object
  NUANCE_SKIP_WELCOME_MESSAGE: 'NUANCE_SKIP_WELCOME_MESSAGE', // If there is no welcome message for sure,
  NUANCE_NLU_ENTITY_VALUE_MODE: 'NUANCE_NLU_ENTITY_VALUE_MODE' // FORCE_LITERAL, FORCE_STRUCT, LITERAL_FOR_COMPLEX// entity can be sting, and struct. Hard to say which is better
}
